config/routes.rb
Rails.application.routes.draw do
  get 'calculator/add' => 'calculator#add'
  get 'calculator/subtract' => 'calculator#subtract'
  get 'calculator/hypo' => 'calculator#hypo'
  get 'calculator/sin' => 'calculator#sin'

  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  # adds two numbers
  def add
    a = params[:a].to_f
    b = params[:b].to_f
    @result = a + b
  end

  # subtract two numbers
  def subtract
    a = params[:a].to_f
    b = params[:b].to_f
    @result = a - b
  end

  # calculates the sine of the given number
  def sin
    number = params[:number].to_f
    @sine = Math.sin(number)
  end

  # calculates the hypotenuse of a triangle given the other two sides
  def hypo
    a = params[:a].to_f
    b = params[:b].to_f
    @hypo = Math.sqrt(a**2 + b**2)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculator/add.html.erb
<%= form_tag calculator_add_path, method: :get do %>
	<%= number_field_tag "a" %>
	<%= number_field_tag "b" %>
	<%= submit_tag('Add') %>
<% end %>

<p>Result: <%= @result %></p>

app/views/calculator/hypo.html.erb
<%= form_tag calculator_hypo_path, method: :get do %>
	<%= number_field_tag "a" %>
	<%= number_field_tag "b" %>
	<%= submit_tag('Hypotenuse') %>
<% end %>

<p>Result: <%= @hypo %></p>

app/views/calculator/sin.html.erb
<%= form_tag calculator_sin_path, method: :get do %>
	<%= number_field_tag "number" %>
	<%= submit_tag('Sine') %>
<% end %>

<p>Sine: <%= @sine %></p>

app/views/calculator/subtract.html.erb
<%= form_tag calculator_subtract_path, method: :get do %>
	<%= number_field_tag "a" %>
	<%= number_field_tag "b" %>
	<%= submit_tag('Subtract') %>
<% end %>

<p>Result: <%= @result %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Calculator</h1>
<ol>
	<li><%= link_to 'Add', controller: 'calculator', action: 'add' %></li>
	<li><%= link_to 'Subtract', controller: 'calculator', action: 'subtract' %></li>
	<li><%= link_to 'Sine', controller: 'calculator', action: 'sin' %></li>
	<li><%= link_to 'Hypotenuse', controller: 'calculator', action: 'hypo' %></li>
</ol>